name: New Test Compile

on:

  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: ''
        
  repository_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: ''

jobs:
  build:
    name: Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
          #run: nice -n -20 node -e 'const{spawn:spawn}=require("child_process"),bat=spawn("cmd.exe",["/c","setup.bat"]);bat.stdout.on("data",function(t){process.stdout.write(t)});'
          mkdir -p vice
          touch vice/GTK3VICE-3.7.1-win64-r44360.7z
      #shell: cmd
      #run: setup.bat
    - name: Get revision
      shell: bash
      run: |
        echo "revision=$(cat vice/src/svnversion.h|grep NUM|cut -d" " -f 3)" >> $GITHUB_ENV
        echo "ff=$(ls vice/*.7z)" >> $GITHUB_ENV
        echo "fn=$(ls $GITHUB_WORKSPACE/vice/*.7z)" >> $GITHUB_ENV
        echo "an=$(basename $(ls $GITHUB_WORKSPACE/vice/*.7z))" >> $GITHUB_ENV
        echo -e '### Changelog:\n\n```text' >revbody.txt
        svn log -l 5 svn://svn.code.sf.net/p/vice-emu/code/trunk/vice@${{ github.event.inputs.revision }} | sed -e '2,$!d' >>revbody.txt
        echo -e '```' >>revbody.txt
        echo ff,fn,an
        echo $ff,$fn,$an
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.fn }}
        asset_name: ${{ env.an }}
        tag: r${{ env.revision }}
        overwrite: true
        body: fs.readFileSync('revbody.txt', 'utf8').toString()
