name: Test Compile

on:

  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: ''
        
  repository_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

    # Runs a single command using the runners shell
      - name: Run build script
        shell: bash
        run: |
           npm install
           node nbuild.js
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path:  vice/*.7z

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Done.
